language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
        - COMPOSER_FLAGS=""
        - MODE="test" # Allowed values: [test, syntax, phpstan]

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.2
          env: DEPENDENCIES=beta
        - php: 7.2
          env: MODE="syntax"
        - php: 7.2
          env: MODE="phpstan"

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
    - if [[ "$MODE" == "syntax" ]]; then composer require --dev --no-update friendsofphp/php-cs-fixer; fi;
    - if [[ "$MODE" == "phpstan" ]]; then composer require --dev --no-update phpstan/phpstan; fi;
    - composer update --prefer-dist --no-progress --no-suggest $COMPOSER_FLAGS --ansi

script:
    - if [[ "$MODE" == "syntax" ]]; then ./vendor/bin/php-cs-fixer fix --dry-run --diff --no-interaction -v; fi;
    - if [[ "$MODE" == "phpstan" ]]; then ./vendor/bin/phpstan analyze -c phpstan.neon -l max src/ tests/; fi;
    - if [[ "$MODE" == "test" ]]; then ./vendor/bin/phpunit; fi;
